export default[
  "food",
  "pizza",
  "nudelz",
  "hello Kitty",
  "animals",
  "pandas",
  "tigers",
  "puppies",
  "dogs",
  "babies",
  "frogs",
  "fish",
  "robots",
  "smart people",
  "famous people",
  "stupid people",
  "short people",
  "tall people",
  "ugly people",
  "good looking people",
  "programmers",
  "entrepreneurs",
  "students",
  "kindergarden",
  "school",
  "old people",
  "blind people",
  "candy",
  "vegans",
  "asians",
  "russians",
  "apple fans",
  "startups",
  "liberals",
  "communists",
  "billionaires",
  "celebrities",
  "party people",
  "ice-cream",
  "people with bizzare fetishes",
  "DJs",
  "music",
  "depressed people",
  "ex-convicts",
  "baristas",
  "texas",
  "the french",
  "cucumbers",
  "beliebers",
  "guys",
  "girls",
  "firefighters",
  "home wifes",
  "alcoholics",
  "the homeless",
  "stormtroopers",
  "people that vapes",
  "fidget spinners",
  "cool people",
  "nerds",
  "the cool kids",
  "your mum",
  "farmers",
  "swedes",
  "the amish",
  "singles near you",
  "Tv",
  "flowers",
  "lamps",
  "fruits",
  "the cloud",
  "astronauts",
  "politicians",
  "athletes",
  "bus drivers",
  "pet owners",
  "teachers",
  "dads",
  "siblings",
  "drivers",
  "horses",
  "waitresses",
  "managers",
  "work",
  "anyone",
  "alpacas",
  "windows phone",
  "gang members",
  "americans",
  "trump supporters",
  "tourists",
  "linux users",
  "less stupid people",
  "mongolians",
  "non facebook people",
  "memes",
  "game developers",
  "mac users",
  "android users",
  "germans",
  "italy",
  "greece",
  "thailand",
  "plants",
  "hipsters",
  "people with glasses",
  "people that uses bing",
  "gamers",
  "boring people",
  "non-humans",
  "bees",
  "life guards",
  "vegetarians",
  "people on vacation",
  "reddit users",
  "boy scouts",
  "science",
  "emergencies only"
];
